name: Automated Python .exe Build (PyInstaller)

# Triggers this workflow on push to main or manual trigger
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_windows_exe:
    # Use the Windows runner
    runs-on: windows-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # IMPORTANT: Set this to the Python version your browser needs

      # Step 3: Install dependencies (including PyInstaller)
      - name: Install Dependencies
        # This assumes your project has a requirements.txt file
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Step 4: Run PyInstaller to create the .exe
      - name: Run PyInstaller Build
        # **CUSTOMIZE THIS COMMAND**
        # 'your_main_script.py' should be the entry point of your browser.
        # '--onefile' creates a single .exe file.
        # Replace 'your_main_script.py' with your actual starting file.
        run: pyinstaller --onefile simple_browser.py
        # You may need to add additional flags like --windowed or --icon

      # Step 5: Upload the final .exe artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Navi-Web-Browser-Installer
          # PyInstaller puts the .exe in the 'dist' folder by default
          # The name will match your main script (e.g., 'your_main_script.exe')
          path: ./dist/*.exe
